//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //AANIMVAR
        /////AMAPPINGSVAR
        ///function d2h(d){return d.toString(16).toUpperCase();};function h2d(h){return parseInt(h,16);};
        ///function tc(obj){var o=obj,id=obj.id;this.o=obj;this.id=id;this.x=(h2d(id)%80)+1;this.y=Math.floor(h2d(id)/80)+1;this.f=&apos;7&apos;;this.b=&apos;0&apos;;this.f2=&apos;7&apos;;this.blink=false;this.r=rc;function rc(back){if(!back){this.o.className=&quot;II&quot;;}else{this.o.className=&quot;b&quot;+back;};this.o.innerHTML=&quot;&amp;nbsp;&quot;;this.f=&apos;7&apos;;this.f2=&apos;7&apos;;this.b=&apos;0&apos;;this.blink=false;};};tc.prototype.sc=function(f,b,bl){this.o.className [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ANSIJS {
            get {
                return ResourceManager.GetString("ANSIJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /////AANIMVAR
        /////AMAPPINGSVAR
        ///
        ///function d2h(d) {return d.toString(16).toUpperCase();}
        ///function h2d(h) {return parseInt(h,16);}
        ///function thiscell(obj) {
        ///   var o=obj; 
        ///   var id=obj.id;
        ///   this.o = obj; 
        ///   this.id=id;
        ///   this.x=(h2d(id) % 80)+1;
        ///   this.y=Math.floor(h2d(id)/80)+1;
        ///   this.resetchr = resetchar;
        ///   function resetchar(back){
        ///      if (!back) {
        ///		this.o.className=&quot;II&quot;; 
        ///	  } else {
        ///	    this.o.className=&quot;b&quot;+back; 
        ///      }	  
        ///	  this.o.innerHTML=&quot;&amp;nbsp;&quot;;
        ///	  this.o.title=this.o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ANSIJS2 {
            get {
                return ResourceManager.GetString("ANSIJS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dosfont80x25c16b2 {
            get {
                object obj = ResourceManager.GetObject("dosfont80x25c16b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dosfont80x50c16b2 {
            get {
                object obj = ResourceManager.GetObject("dosfont80x50c16b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dosfontback16c {
            get {
                object obj = ResourceManager.GetObject("dosfontback16c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dosfontback16c1 {
            get {
                object obj = ResourceManager.GetObject("dosfontback16c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ffmpeg {
            get {
                object obj = ResourceManager.GetObject("ffmpeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fnt80x25 {
            get {
                object obj = ResourceManager.GetObject("fnt80x25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fnt80x50 {
            get {
                object obj = ResourceManager.GetObject("fnt80x50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
