//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	internal class Resources
	{

		private global::System.Resources.ResourceManager resourceMan;

		private global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		internal byte[] ANSIJS {
			get {
				object obj = ResourceManager.GetObject("ANSIJS", resourceCulture);
				return (byte[])obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		internal byte[] ANSIJS2 {
			get {
				object obj = ResourceManager.GetObject("ANSIJS2", resourceCulture);
				return (byte[])obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		internal System.Drawing.Bitmap dosfont80x25c16b2 {
			get {
				object obj = ResourceManager.GetObject("dosfont80x25c16b2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		internal System.Drawing.Bitmap dosfont80x50c16b2 {
			get {
				object obj = ResourceManager.GetObject("dosfont80x50c16b2", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		internal System.Drawing.Bitmap dosfontback16c {
			get {
				object obj = ResourceManager.GetObject("dosfontback16c", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		internal byte[] ffmpeg {
			get {
				object obj = ResourceManager.GetObject("ffmpeg", resourceCulture);
				return (byte[])obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		internal System.Drawing.Bitmap fnt80x25 {
			get {
				object obj = ResourceManager.GetObject("fnt80x25", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		internal System.Drawing.Bitmap fnt80x50 {
			get {
				object obj = ResourceManager.GetObject("fnt80x50", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}